# Generated by Django 4.1.7 on 2023-05-10 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('relationship_to_person', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=200)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('missing_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missing_person_contacts', to='base.missingperson')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('contact_info', models.CharField(max_length=200)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('missing_person_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.missingperson')),
            ],
        ),
        migrations.AddField(
            model_name='missingperson',
            name='contacts',
            field=models.ManyToManyField(to='base.contact'),
        ),
    ]
