# Generated by Django 4.1.7 on 2023-07-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_user_id_missingperson_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='image',
            field=models.ImageField(blank=True, default='/logo1.png', null=True, upload_to=''),
        ),
    ]
