# Generated by Django 4.1.7 on 2023-05-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_missingperson_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_primary_contact',
            field=models.BooleanField(default=False),
        ),
    ]
