# Generated by Django 4.1.7 on 2023-05-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_contact_is_primary_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingperson',
            name='contacts',
        ),
        migrations.AddField(
            model_name='missingperson',
            name='primary_contact_first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='primary_contact_last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='primary_contact_phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='secondary_contact_first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='secondary_contact_last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='secondary_contact_phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
