# Generated by Django 4.1.7 on 2023-07-04 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_missingperson_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missingperson',
            old_name='user_id',
            new_name='user',
        ),
    ]
