export const MISSINGPERSON_LIST_REQUEST = "MISSINGPERSON_LIST_REQUEST";
export const MISSINGPERSON_LIST_SUCCESS = "MISSINGPERSON_LIST_SUCCESS";
export const MISSINGPERSON_LIST_FAIL = "MISSINGPERSON_LIST_FAIL";