export const missingPersons = [
  {
    _id: "1",
    first_name: "John",
    last_name: "Doe",
    image: "/images/logo.png",
    age_last_seen: "52",
    gender: "male",
    hair: "black",
    eyes: "green",
    height: 1.65,
    weight: 80,
    last_seen_wearing: "Blue jeans, black t-shirt, gray hoodie",
    critical_information: "mental health concerns",
    circumstances_of_disappearance:
      "John was last seen leaving his apartment building on foot. He did not take his car or phone with him. He has no known history of mental health issues or substance abuse.",
    province: "Azua",
    last_known_location: "123 Main Street, Anytown, USA",
    date_and_time_last_seen: "March 1, 2023 at 2:00 PM",
    name_of_contact: "Janet Doe",
    phone_number_of_contact: "111-111-1111",
    name_of_contact_2: "Janet Twin Doe",
    phone_number_of_contact_2: "121-111-1111",
  },
  {
    _id: "2",
    first_name: "Jane",
    last_name: "Doe",
    image: "/images/logo.png",
    age_last_seen: "52",
    gender: "male",
    hair: "black",
    eyes: "green",
    height: 1.65,
    weight: 80,
    last_seen_wearing: "Blue jeans, black t-shirt, gray hoodie",
    critical_information: "mental health concerns",
    circumstances_of_disappearance:
      "John was last seen leaving his apartment building on foot. He did not take his car or phone with him. He has no known history of mental health issues or substance abuse.",
    province: "Azua",
    last_known_location: "123 Main Street, Anytown, USA",
    date_and_time_last_seen: "March 1, 2023 at 2:00 PM",
    name_of_contact: "Janet Doe",
    phone_number_of_contact: "111-111-1111",
    name_of_contact_2: "Janet Twin Doe",
    phone_number_of_contact_2: "121-111-1111",
  },
  {
    _id: "3",
    first_name: "John",
    last_name: "Doe",
    image: "/images/logo.png",
    age_last_seen: "52",
    gender: "male",
    hair: "black",
    eyes: "green",
    height: 1.65,
    weight: 80,
    last_seen_wearing: "Blue jeans, black t-shirt, gray hoodie",
    critical_information: "mental health concerns",
    circumstances_of_disappearance:
      "John was last seen leaving his apartment building on foot. He did not take his car or phone with him. He has no known history of mental health issues or substance abuse.",
    province: "Azua",
    last_known_location: "123 Main Street, Anytown, USA",
    date_and_time_last_seen: "March 1, 2023 at 2:00 PM",
    name_of_contact: "Janet Doe",
    phone_number_of_contact: "111-111-1111",
    name_of_contact_2: "Janet Doe",
    phone_number_of_contact_2: "121-111-1111",
  },
  {
    _id: "4",
    first_name: "Terry",
    last_name: "Coats",
    image: "/images/logo.png",
    age_last_seen: "52",
    gender: "male",
    hair: "black",
    eyes: "green",
    height: 1.65,
    weight: 80,
    last_seen_wearing: "Blue jeans, black t-shirt, gray hoodie",
    critical_information: "mental health concerns",
    circumstances_of_disappearance:
      "John was last seen leaving his apartment building on foot. He did not take his car or phone with him. He has no known history of mental health issues or substance abuse.",
    province: "Azua",
    last_known_location: "123 Main Street, Anytown, USA",
    date_and_time_last_seen: "March 1, 2023 at 2:00 PM",
    name_of_contact: "Janet Doe",
    phone_number_of_contact: "111-111-1111",
    name_of_contact_2: "Janet Doe",
    phone_number_of_contact_2: "121-111-1111",
  },
  {
    _id: "5",
    first_name: "James",
    last_name: "Simmons",
    image: "/images/logo.png",
    age_last_seen: "52",
    gender: "male",
    hair: "black",
    eyes: "green",
    height: 1.65,
    weight: 80,
    last_seen_wearing: "Blue jeans, black t-shirt, gray hoodie",
    critical_information: "mental health concerns",
    circumstances_of_disappearance:
      "John was last seen leaving his apartment building on foot. He did not take his car or phone with him. He has no known history of mental health issues or substance abuse.",
    last_known_location: "123 Main Street, Anytown, USA",
    province: "Azua",
    date_and_time_last_seen: "March 1, 2023 at 2:00 PM",
    name_of_contact: "Janet Doe",
    phone_number_of_contact: "111-111-1111",
    name_of_contact_2: "Janet Doe",
    phone_number_of_contact_2: "121-111-1111",
  },
  {
    _id: "6",
    first_name: "Shirly",
    last_name: "Chu",
    image: "/images/logo.png",
    age_last_seen: "52",
    gender: "male",
    hair: "black",
    eyes: "green",
    height: 1.65,
    weight: 80,
    last_seen_wearing: "Blue jeans, black t-shirt, gray hoodie",
    critical_information: "mental health concerns",
    circumstances_of_disappearance:
      "John was last seen leaving his apartment building on foot. He did not take his car or phone with him. He has no known history of mental health issues or substance abuse.",
    province: "Azua",
    last_known_location: "123 Main Street, Anytown, USA",
    date_and_time_last_seen: "March 1, 2023 at 2:00 PM",
    name_of_contact: "Janet Doe",
    phone_number_of_contact: "111-111-1111",
    name_of_contact_2: "Janet Doe",
    phone_number_of_contact_2: "121-111-1111",
  },
];
